let tasks = JSON.parse(localStorage.getItem('studyNebulaTasks')) || [];
let darkMode = localStorage.getItem('darkMode') !== 'false';

document.addEventListener('DOMContentLoaded', () => {
    renderTasks();
        updateStats();
            setupDarkMode();
            });

            function addTask() {
                const input = document.getElementById('taskInput');
                    const taskText = input.value.trim();
                        
                            if (taskText) {
                                    tasks.unshift({
                                                id: Date.now(),
                                                            text: taskText,
                                                                        completed: false,
                                                                                    created: new Date().toLocaleDateString()
                                                                                            });
                                                                                                    
                                                                                                            input.value = '';
                                                                                                                    saveTasks();
                                                                                                                            renderTasks();
                                                                                                                                    updateStats();
                                                                                                                                        }
                                                                                                                                        }

                                                                                                                                        function toggleComplete(id) {
                                                                                                                                            tasks = tasks.map(task => 
                                                                                                                                                    task.id === id ? { ...task, completed: !task.completed } : task
                                                                                                                                                        );
                                                                                                                                                            saveTasks();
                                                                                                                                                                renderTasks();
                                                                                                                                                                    updateStats();
                                                                                                                                                                    }

                                                                                                                                                                    function deleteTask(id) {
                                                                                                                                                                        tasks = tasks.filter(task => task.id !== id);
                                                                                                                                                                            saveTasks();
                                                                                                                                                                                renderTasks();
                                                                                                                                                                                    updateStats();
                                                                                                                                                                                    }

                                                                                                                                                                                    function renderTasks() {
                                                                                                                                                                                        const taskList = document.getElementById('taskList');
                                                                                                                                                                                            taskList.innerHTML = '';
                                                                                                                                                                                                
                                                                                                                                                                                                    tasks.forEach((task) => {
                                                                                                                                                                                                            const li = document.createElement('li');
                                                                                                                                                                                                                    li.className = `task-item ${task.completed ? 'completed' : ''}`;
                                                                                                                                                                                                                            li.innerHTML = `
                                                                                                                                                                                                                                        <div class="task-content">
                                                                                                                                                                                                                                                        <span class="task-text">${task.text}</span>
                                                                                                                                                                                                                                                                        <small class="task-date">${task.created}</small>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                <div class="task-buttons">
                                                                                                                                                                                                                                                                                                                <button class="btn-complete" onclick="toggleComplete(${task.id})">
                                                                                                                                                                                                                                                                                                                                    ${task.completed ? '↺ Undo' : '✅ Done'}
                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                    <button class="btn-delete" onclick="deleteTask(${task.id})">🗑️</button>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                taskList.appendChild(li);
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                    function updateStats() {
                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('totalTasks').textContent = tasks.length;
                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('completedTasks').textContent = 
                                                                                                                                                                                                                                                                                                                                                                                                                    tasks.filter(t => t.completed).length;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                    function saveTasks() {
                                                                                                                                                                                                                                                                                                                                                                                                                        localStorage.setItem('studyNebulaTasks', JSON.stringify(tasks));
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                        function setupDarkMode() {
                                                                                                                                                                                                                                                                                                                                                                                                                            const toggle = document.getElementById('darkToggle');
                                                                                                                                                                                                                                                                                                                                                                                                                                if (toggle) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        toggle.checked = darkMode;
                                                                                                                                                                                                                                                                                                                                                                                                                                                toggle.addEventListener('change', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            darkMode = e.target.checked;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        localStorage.setItem('darkMode', darkMode);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.body.classList.toggle('light-mode', !darkMode);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('taskInput').addEventListener('keypress', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (e.key === 'Enter') addTask();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });